[platformio]
boards_dir = boards
[env:t5pro]
platform = espressif32@6.12.0
framework = arduino
board = T5-ePaper-S3-Pro
upload_speed = 921600
monitor_speed = 115200
build_flags =
	-DBOARD_HAS_PSRAM
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_USB_MODE=1
	-DCORE_DEBUG_LEVEL=3
	-DDISABLE_ALL_LIBRARY_WARNINGS
lib_deps = Wire, SPI
